### ISSUE TITLE
Quality of life addons to the mod

### ISSUE THREAD

**Issue by battery3996** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#13]
It would be great if we could get feedback when we whitelist someone on the server for cci
```
Console:
/cci whitelist {username}
{username} is now whitelisted to use CCI rewards
```

Also any possible way for the OP players to add people to the CCI whitelist from within game? I have been asked by alot of streamers who have used my preset from reddit, "Hey is your preset broken? I whitelisted myself and they wont trigger." My response is normally, "Did you whitelist your self using the command in console? not within game but the actual console." So many try to do the whitelist from within the game itself.

**Comment by iChun** [comment]
I tell the client that they need to use the server console if they try to do /cci whitelist on the client now. Thanks!
