### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by blacknight2u** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#15]
the website under Event Configuration "Read about it in more detail here." is down.
Would be nice if there was a bit more info on how to use this mod. I am struggling trying to set it up.
want a chat to command to summon a wolf.
can't figure out how to setup a trigger ie; If chat == "!summon" do x
Have read the entire CCI website ~5 times and am still lost.
Thx for all the awesome mods!

**Comment by iChun** [comment]
The documentation has finally been set up properly and all links should point to the right places. https://content-creator-integration.readthedocs.io/en/latest
