### ISSUE TITLE
[Requested Feature] Make certain CCI rewards an once in stream type thing

### ISSUE THREAD

**Issue by battery3996** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#17]
So with some rewards that have been written, is there by chance we can get a option to say, "Make this reward happen once per stream or Session load." 

EXAMPLE: 
``````
CCI is detecting when someone hosts, reward happens
same person unhosts and hosts again 
same reward happens again
``````

or 

``````
Summon dragon for 100000 bits 
this reward can only be triggered once per session
``````

**Comment by iChun** [comment]
Make a note array for "hosts this session", when someone hosts, use a condition to check if they've hosted in the note, then do the reward, add them to the note. On init of session, clear or delete the note.

That should accomplish what you want. You can also try using global variables in place of notes. Global variables will always be per session so you don't have to delete them after.

**Comment by iChun** [comment]
Since the main issue should have been handled, I am closing this.
