### ISSUE TITLE
inverseMatch doesnt flip true to false.

### ISSUE THREAD

**Issue by kbigliar** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#19]
I set up 2 test components in the document: https://pastebin.com/exeYdM0b such that it should only run one component or the other as they have inverse conditions. When using the "kbigliar" account in twitch chat, I triggered both components. When using a different account, i only triggered the second component. Tests are shown in this link : https://imgur.com/a/X8l5Rfn .

**Comment by iChun** [comment]
Sorry for the delay. This issue will be fixed in v1.1.0. Thanks for the issue report!
