### ISSUE TITLE
No hurt Damage

### ISSUE THREAD

**Issue by battery3996** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#2]
So i have been messing with the mod and i have noticed that the HealthOutcome doesn't do damage. So you have it in the notes that positive values heal but negative values hurt. Positive values do heal. However when I set a value to a negative, it plays a sound as if I was damaged but no damage actually comes out of it.

**Comment by iChun** [comment]
Just to make a note, busy IRL, will look into the code when I can.

**Comment by iChun** [comment]
Fixed for v1.0.1
