### ISSUE TITLE
noteContent in NoteOutcome does not support variable insertion

### ISSUE THREAD

**Issue by kbigliar** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#20]
As seen in this picture, https://imgur.com/a/EQVGtYN , I tried to save the message into a note and then printed out the note. I also had 2 other events above: one printing <filler outcomes> and another displaying the number of terms in the note, who said a chat msg, and what the message was. 

I copied the variable from the working event to the note addition to verify it was not a typo.

Here is the text document: https://pastebin.com/h9iLa9cv

**Comment by iChun** [comment]
Sorry that was a bug with writing to notes in an array. It will be fixed in 1.1.0.
