### ISSUE TITLE
Arithmetic Conditions not working for streamlabs donations

### ISSUE THREAD

**Issue by darkphan** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#21]
Trying to divide the amount donated by 5 (or any other arithmetic operation) causes the outcome not to trigger.

Example Config: https://pste.me/#/MwA3W

**Comment by kbigliar** [comment]
If you save the $amount into a different variable arithmetic operations should work it should work.

**Comment by darkphan** [comment]
Ah yes, and to think I had done that in the past lol. Thanks.

**Comment by iChun** [comment]
I'm going to mark this as resolved for the moment. If you're still having any problems with the mod please feel free to make a new issue!
