### ISSUE TITLE
[Feature Request] A Drop command

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#24]
I know this seems a little out of context for your mod but heres my idea...

Using your mod Streamers can !redeem items from the Twitch store thru Twitch Chat which is great. I have a mystery item that has a chance to change the players head

The problem is that whatever item is in the players head slot gets deleted.  I can not find any command that would drop an item on request from the players inventory.

So a '/Drop Slot #1' command would drop the players head item and I can safely replace it.  Or any slot item in the players inventory.

**Comment by iChun** [comment]
DropItemOutcome will be a thing in v1.1.0
