### ISSUE TITLE
YT and Twitch Tokens are different

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#25]
I use StreamElements. The YT and Twitch tokens are different. Could you adapt your config file to store both tokens. And maybe a command to easily switch connection between the two while in game?

thank you

**Comment by iChun** [comment]
For the socket token? That's new. No one has informed me about this, I'll
have a look soon.

**Comment by MeinKraft** [comment]
Im editing the configs for a YouTuber/Twitcher called StompTheBean.  Using his Twitch token everything works 100%. We can monitor Twitch chat, redeem from the Twitch store, monitor followers/subs etc  perfect.

He informed me that the YT side didnt work. Subscribers werent showing up.

He streams 2 hours on YT and then 2 Hours on Twitch immediately after.  I changed the config to use the YT token and a subscriber showed up in Minecraft chat - perfect - but nothing from Twitch later the same night using the YT token

The YT test was using the default configs that CCI creates


As a side question, is it possible to detect Tips/SubGifts from Twitch? I have created 2 events called 'tip' and 'donation' but so far they have not been triggered (this was just guess work on my behalf).

I found an example of StreamLabs config that someone made and that has 'donation' and 'subMysteryGift' event types. Are these the same for StreamElements?

**Comment by iChun** [comment]
Sorry for the delay. Multiple tokens from the same platform will be supported in version 1.1.0.

Yes it's possible to detect tips and sub gifts from twitch. I'm not familiar with the ID as streamelements and streamlabs both have their own labels for them. (You should go through the logs when these events happen (from the streamer) as they will have the information you need to build those events. If people were to contribute to CCI's documentation as well it'd help other people who are currently stuck with these sort of issues.)
