### ISSUE TITLE
2 new Variables please

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#26]
Could we please have 2 variables added to CCI

1 variable to count the iteration of a RepeatOutcome event.  So if we repeat something 10 times, we could do Spawn Rabbit Name "Sub Month $Iteration", would spawn 10 rabbits. one called "Sub Month 1", "Sub Month 2" etc

1 variable as a Counter.  When people cheer/subscribe/follow we can add an amount to the Counter.  When Counter equals a certain amount we trigger an event.  Cheer/sub/follow could set different amounts to counter. And an event for when value of Coutner changes, so we could maybe display a message on screen

thank you

**Comment by iChun** [comment]
I didn't realise the RepeatOutcome didn't tell you the iteration count. That value will be in $iteCount in CCI 1.1.0.

#2 should be possible using ArithmeticConditions and RangedValueConditions after in MultipleOutcomeOutcome and ConditionalOutcomes
