### ISSUE TITLE
DonationAlerts Support?

### ISSUE THREAD

**Issue by omjoskaro** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#30]
Can I create Donation Alerts  event about donations in Ruble currency? In mod config i'am find donation in Streamlabs services, but DonationAlerts  donation events i cant find!
![Screenshot_1](https://user-images.githubusercontent.com/41262836/67799199-9ba31600-fa8d-11e9-87bf-777982619887.png)
![Screenshot_2](https://user-images.githubusercontent.com/41262836/67799200-9ba31600-fa8d-11e9-9198-dd6e54d8fb69.png)

**Comment by omjoskaro** [comment]
Please correct information about DonationAlerts  on your site!

**Comment by iChun** [comment]
Sorry for the delay in replying. Most alerts that come through DonationAlerts will be logged to the log file CCI makes, I'll either have to go through this file to figure out what went wrong and if any change needs to be made on my end. From your issue alone I do not have enough information to resolve this.

DonationAlerts doesn't really have any proper documentation on how things work so I have to work things out by trial and error and I don't use their system so it's a bit hard for me to do so.

**Comment by iChun** [comment]
From what I can tell, Donation Alerts support is still in the mod even though no one has stepped up to kind of mess around with it enough or provide configs I could use for defaults. As mentioned, I don't use their service personally so it's hard for me to provide support for something I don't use. 

With the new CCI (1.5.0+) it would be much easier to figure out how events work and how to handle them in the editor. I'm going to close this issue. If someone can post information that can confirm that support is broken, please post it in a new issue.
