### ISSUE TITLE
Server CCI OP requirement

### ISSUE THREAD

**Issue by sublimiter** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#32]
Hi iChun, 

Upon attempting to use your mod on our server, my friends and I have come across an issue.

While the mod is supposed to work for any user without op status on the server, at this point in time, that isn't the case.
In order to allow a user to use CCI on the server, the user is required to be op'd.

Could you please look into this when you have a chance, as my friends and I are keen on using CCI on our server, but are concerned about potential new players on the server that we might not know so well requiring op status in order to use the mod, thus opening up a vulnerability in the server.

Thanking you in advance for your help with this.

Kind regards,
Sublimiter

**Comment by iChun** [comment]
Discussed privately. Seems to be a non-issue. Closing for now. Feel free to make a new issue if this persists.
