### ISSUE TITLE
[Feature Request] Add Channel Points Support

### ISSUE THREAD

**Issue by TimRambo** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#33]
I believe its this
https://dev.twitch.tv/docs/pubsub

And here is a screenshot of what i am talking about
https://timrambo.eu/i/ddn.png

Its another way for people to interact with your gameplay :)

**Comment by battery3996** [comment]
There is already channel point support. It's under the twitch chat setup. Channel point redeemtion just needs a msg so that it send the custom reward id

**Comment by TimRambo** [comment]
> There is already channel point support. It's under the twitch chat setup. Channel point redeemtion just needs a msg so that it send the custom reward id

ah ok, thanks :)

**Comment by battery3996** [comment]
Even tho you labeled it closed, i wanted to give you an example of how its setup. 

Dumped event:
"id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
      "args": {
        "user-type": "",
        "tmi-sent-ts": "1577680045769",
        "cci-type-event": "message",
        "mod": "0",
        "subscriber": "0",
        "color": "#8A2BE2",
        "playerName": "Battery3996",
        "turbo": "0",
        "user-id": "35820266",
        "flags": "",
        "message": "#babyBatts",
        **"custom-reward-id": "4de58110-fba0-4bd4-b503-4edbd5bc3170",**
        "platform": "twitch",
        "streamer": "Battery3996",
        "room-id": "55567498",
        "cci-type-for": "twitch",
        "display-name": "xxxxxxxxxx",
        "configId": 1,
        "emotes": "",
        "name": "xxxxxxxxxxx",
        "badges-premium": "1",
        "cci-type-config": "chat",
        "user": "xxxxxxxxxxxx",
        "badge-info": ""
      }
    },

Reward setup
{
            "name": "Creeper Twitch points",
            "conditions": [
              {
                "variableName": "custom-reward-id",
                **"variableResult": "4de58110-fba0-4bd4-b503-4edbd5bc3170",**
                "type": "variable"
              }
            ],
            "outcomes": [
              {
                "command": "/execute at $playerName run summon minecraft:creeper ~ ~1 ~ {powered:1,CustomName:\"\\\"boom\\\"\",CustomNameVisible:1,PersistenceRequired:1b,Glowing:1,Health:200,Attributes:[{Name:\"generic.maxHealth\",Base:200},{Name:\"generic.followRange\",Base:0},{Name:\"generic.knockbackResistance\",Base:1f},{Name:\"generic.movementSpeed\",Base:0f}],Silent:1,ExplosionRadius:0,Fuse:20,ignited:1}",
                "type": "command"
              },
              {
                "message": "$user redeemed creeper!",
                "inActionBar": true,
                "type": "chat"
              }
            ],
            "playTime": 100,
            "delay": 60
          }

bold is what twitch sends and what you need to add to the reward in the conditions.

**Comment by battery3996** [comment]
Each custom channel point reward has its own separate custom id code

**Comment by TimRambo** [comment]
> Even tho you labeled it closed, i wanted to give you an example of how its setup.
> 
> Dumped event:
> "id": "xxxxxxxxxxxxxxxxxxxxxxxxx",
> "args": {
> "user-type": "",
> "tmi-sent-ts": "1577680045769",
> "cci-type-event": "message",
> "mod": "0",
> "subscriber": "0",
> "color": "#8A2BE2",
> "playerName": "Battery3996",
> "turbo": "0",
> "user-id": "35820266",
> "flags": "",
> "message": "#babyBatts",
> **"custom-reward-id": "4de58110-fba0-4bd4-b503-4edbd5bc3170",**
> "platform": "twitch",
> "streamer": "Battery3996",
> "room-id": "55567498",
> "cci-type-for": "twitch",
> "display-name": "xxxxxxxxxx",
> "configId": 1,
> "emotes": "",
> "name": "xxxxxxxxxxx",
> "badges-premium": "1",
> "cci-type-config": "chat",
> "user": "xxxxxxxxxxxx",
> "badge-info": ""
> }
> },
> 
> Reward setup
> {
> "name": "Creeper Twitch points",
> "conditions": [
> {
> "variableName": "custom-reward-id",
> **"variableResult": "4de58110-fba0-4bd4-b503-4edbd5bc3170",**
> "type": "variable"
> }
> ],
> "outcomes": [
> {
> "command": "/execute at $playerName run summon minecraft:creeper ~ ~1 ~ {powered:1,CustomName:"\"boom\"",CustomNameVisible:1,PersistenceRequired:1b,Glowing:1,Health:200,Attributes:[{Name:"generic.maxHealth",Base:200},{Name:"generic.followRange",Base:0},{Name:"generic.knockbackResistance",Base:1f},{Name:"generic.movementSpeed",Base:0f}],Silent:1,ExplosionRadius:0,Fuse:20,ignited:1}",
> "type": "command"
> },
> {
> "message": "$user redeemed creeper!",
> "inActionBar": true,
> "type": "chat"
> }
> ],
> "playTime": 100,
> "delay": 60
> }
> 
> bold is what twitch sends and what you need to add to the reward in the conditions.

ye that would def help thanks :D

**Comment by TimRambo** [comment]
> Each custom channel point reward has its own separate custom id code

sorry to disturb u but where those that config file go ?
and the /cci edit for me is just a mess but that might just be me xD

**Comment by iChun** [comment]
Like @battery3996 mentioned, Channel Points are supported at the moment, but only channel points that require a text input. You have to check that the "custom-reward-id" variable exists from the chat event and act accordingly. The message from the text input still gets sent into $message as usual.

To get the reward id however, I'm not too sure how to get that other than to manually trigger the reward at least once first to get that ID.

I'm going to pin this issue for other people who might come looking asking the same thing. I might support pubnub in the future but for the time being streamlabs/streamelements covers most of that support for now.

**Comment by Shindur** [comment]
What would the type be labeled as? For example, in my chat.json file there's message and action as types with their conditions and outcomes. I read over the above sample reward area and most of the is straight forward, but I'm unsure what the type would be. Any help would be appreciated!

**Comment by iChun** [comment]
Message. Channel rewards with text are messages with an attached channel
reward id

**Comment by iChun** [comment]
Sorry to necro an old issue, but for anyone curious, there's an official tutorial now on the [docs](https://content-creator-integration.readthedocs.io/en/latest/gettingstarted/processingevent/) for both twitch chat and pubsub
