### ISSUE TITLE
Scrollwheel Doesn't Work

### ISSUE THREAD

**Issue by EnderGamingFilms** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#34]
I am trying to look at the variables in the cci edit menu but when I scroll nothing happens. It says the list is scrollable but it isn't working. Is there anywhere I can just view all the variables?

**Comment by iChun** [comment]
Use "/cci dump" in the chat as a workaround for the moment. It dumps the
variables and their values to a dump.json in a much more readable format.

The GUI is currently scheduled to be revamped so I probably will not be
fixing the scroll issue for the time being.

**Comment by EnderGamingFilms** [comment]
Ok thanks :)

**Comment by iChun** [comment]
Fixed in 1.5.0+
