### ISSUE TITLE
Delay corrections in need

### ISSUE THREAD

**Issue by sublimiter** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#36]
I was able to find a "fault" with CCI I would like you to look at when you get a chance. (When I say fault, it doesn't break CCI, just a function doesn't work as expected)

When making an event, I am able to set a delay on the parent event as per usual, but when creating a child event within a repeat outcome, the delay no longer works (So the idea here is to use the repeat outcome for a continued subscriber to spawn multiple spawns, but instead of adding a command outcome to the repeat outcome so all spawns spawn at the same time, I had tried to add iterations by calling on a child event outcome to slow down the spawns with a delay, but the delay in the child event doesn't add a delay to each of the spawns)

Sorry for the long message buddy, I just wanted to make sure that you clearly understood where the location of the error is, to save you some time if and when you get a chance to view it and or fix it.

**Comment by iChun** [comment]
![image](https://user-images.githubusercontent.com/2298444/78579868-2883a400-7864-11ea-84c5-864668ddd910.png)

This diagram was helpful! No code changes required. Closing.
