### ISSUE TITLE
Visual glitch in GUI

### ISSUE THREAD

**Issue by Qeelin** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#39]
After installing the new 1.15.2 version when I edit a command the box that usually pops up on top of everything seems to have moved to the back. You can see it in the gray areas between each column in the screen shot provided. I am unable to edit any commands due to this problem.

I have only one other mod installed, Journey Map, and I'm running forge-31.1.24

![CCI Error](https://user-images.githubusercontent.com/49502544/77762104-0178d700-7007-11ea-9d40-e6112237b9bf.PNG)

Thanks!

**Comment by Shindur** [comment]
Same issue here. Using forge 31.1.30. Not sure how to go about doing it in the actual file either

**Comment by iChun** [comment]
Will be fixed in 1.2.4.
