### ISSUE TITLE
Buttons to add and delete are missing in version 1.15.2

### ISSUE THREAD

**Issue by Qeelin** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#41]
The buttons to add and delete are missing on the most recent version of CCI.
![CCI Error 2](https://user-images.githubusercontent.com/49502544/78508690-70b0a280-774e-11ea-9938-54337260978a.png)

**Comment by iChun** [comment]
Fixed for 1.2.4. It was the same issue as the edit window being lost in the background.
