### ISSUE TITLE
subMysteryGift for StreamLabs isn't working?

### ISSUE THREAD

**Issue by Shindur** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#42]
I'm having issues getting the subMysteryGift to work properly. Below is what I have in my streamlabs.json file for subMysteryGift. Within Streamlabs I setup a subscription variation within the minimums and test it out, but not even the toast pops up in the top right. Everything else I've setup works, just this one doesn't work. Am I doing something wrong or?

` "subMysteryGift": [
          {
            "name": "Sub Gift Notification",
            "conditions": [],
            "outcomes": [
              {
                "toastType": 2,
                "title": "Gifted Subs",
                "subtitle": "$name gifted $amount subs",
                "type": "toast"
              }
            ],
            "allowsOtherEventsToTrigger": true,
            "playTime": 20
          },
          {
            "name": "5 gifted subs Lucky ore where you stand",
            "conditions": [
              {
                "modId": "luckyores",
                "type": "modExists"
              },
              {
                "min": 5.0,
                "max": 9.0,
                "type": "range"
              }
            ],
            "outcomes": [
              {
                "command": "/execute at @a run setblock ~ ~-1 ~ luckyores:baseluckyore replace",
                "type": "command"
              }
            ]
          },
          {
            "name": "10 gifted subs Bad Lucky Ore where you stand",
            "conditions": [
              {
                "modId": "luckyores",
                "type": "modExists"
              },
              {
                "min": 10.0,
                "max": 19.0,
                "type": "range"
              }
            ],
            "outcomes": [
              {
                "command": "/execute at @a run setblock ~ ~-1 ~ luckyores:badluckyore replace",
                "type": "command"
              }
            ]
          },
          {
            "name": "20 Gifted Sub Wither Spawn",
            "conditions": [
              {
                "min": 20.0,
                "max": 49.0,
                "type": "range"
              }
            ],
            "outcomes": [
              {
                "command": "/execute at @a run summon minecraft:wither ~ ~1 ~",
                "type": "command"
              }
            ]
          },
          {
            "name": "50 Gifted Subs Dragon Spawn",
            "conditions": [
              {
                "min": 50.0,
                "max": 99.0,
                "type": "range"
              }
            ],
            "outcomes": [
              {
                "command": "/execute at @a run summon minecraft:ender_dragon ~ ~1 ~",
                "type": "command"
              }
            ]
          },
          {
            "name": "100 Gifted Subs Clear Inventory",
            "conditions": [
              {
                "amount": 100.0,
                "type": "amount"
              }
            ],
            "outcomes": [
              {
                "command": "/execute at @a /clear",
                "type": "command"
              }
            ]
          }
        ],`

**Comment by iChun** [comment]
I'm not sure if Streamlabs changed the type. Could you show me your full streamlabs.json file for me to have a look at? I might have to look at your logs as well to look at the raw data. I've not had any other streamers ask me about this so I thought it was working fine.

**Comment by Shindur** [comment]
Sure, I'll attach both so you have them.

Streamlabs.json: https://pastebin.com/ESVux1vB
Log: https://gist.github.com/Shindur/57190d6c1c6e32450f76ded328816dcc

Had to use gist on the second as I'm not a pastebin pro user.

**Comment by iChun** [comment]
I've had a look, 2 things I've noticed:
1 - your set your sub gift type to "SUBSCRIPTION_GIFT". It has to be subMysteryGift.
2 - your log doesn't show any gift subs actually happening.

I've asked around with some streamers who use CCI and they tell me there's been no changes and subMysteryGift should still be working.

**Comment by Shindur** [comment]
I had changed it to that after making the issue, seeing if that might've fixed it after ruffling through the logs. Also, does setting up a sub variant on streamlabs of "User has gifted <amount> subs at once" and setting it to the minimum of the event to test not work?

**Comment by iChun** [comment]
It does not. Those variants are for the AlertBox. CCI receives events for the AlertBox as well, as well as StreamLabels. That also reminds me, make sure you have a Streamlabs widget open or else CCI (for some reasons) does not receive real world events, but will receive test events (As mentioned in the config). 

Also, Streamlabs' test examples have never really been proper examples of the real events. There are some data that's only in test examples and some only in real examples, which is why I had to look at the log.

As mentioned I've spoken to some other streamers who use CCI. "subMysteryGift" works fine for them in regards to Gift Subs.

**Comment by Shindur** [comment]
Alright, then I'm going to assume what I have would work if any gift subs come through. Thank you for clarifying iChun!

**Comment by iChun** [comment]
Alright, don't forget to switch it back to subMysteryGift!
