### ISSUE TITLE
Commands issued on a server are truncated

### ISSUE THREAD

**Issue by Qeelin** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#43]
I created and tested a command event that is too long for the chat window and it works fine in single player but when I'm on a server that doesn't have CCI the command is cut short.

Version 1.15.2-1.4.3

**Comment by iChun** [comment]
In Single Player the "server" you're connected to allows you to send commands using the channel. That has a character limit of in the ten thousands.

On servers without CCI you are stuck with the chat fallback. That has a hardcoded cap of 256 characters. It's a fallback for a reason and there's nothing I can do about it.
