### ISSUE TITLE
Scroll wheel doesn't scroll windows in UI version 1.15.2-1.4.3

### ISSUE THREAD

**Issue by Qeelin** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#44]
None of the windows will scroll with the scroll wheel in the UI in version 1.15.2-1.4.3.
Version 1.12.2-1.4.3 works fine.

**Comment by iChun** [comment]
Duplicate https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/issues/44
