### ISSUE TITLE
Minecraft goes into loading loop

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#45]
Forge 31.1.47
CCI 1.152-1.5.0

With just JEI, Forge and CCI, Minecraft never finishes loading, it goes into a loop flashing between these 2 images

[https://imgur.com/a/HKvt7ip](https://imgur.com/a/HKvt7ip)

In my modpack however, I get a crash that indicates CookingForBlockheads causes the crash - However checking the latest.log I see theres a CCI problem at line 62

[https://pastebin.com/FiF4J1gc](https://pastebin.com/FiF4J1gc)

**Comment by Direwolf20-MC** [comment]
I'm getting the same thing.

**Comment by Qeelin** [comment]
Make sure you have quotes around your channel name in the config.

**Comment by MeinKraft** [comment]
mine was a new instance in twitch launcher, the configs would have been generated brand new

**Comment by iChun** [comment]
https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/issues/46

**Comment by MeinKraft** [comment]
issue seems fixed. looking forward to experimenting with this new version

thank you.

**Comment by iChun** [comment]
OH RIGHT I forgot to comment on here that it's fixed in 1.5.1. Thanks!
