### ISSUE TITLE
Twitch Chat Disconnected - many notifications

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#47]
Forge: 31.1.47
CCI: 1.15.2-1.5.1

So my internet cut out and for the next minute or so I got constant notifications saying Twitch Chat Disconnected, then I started to get 3 notifications at a time

my config says `maxAutomaticReconnects=3`

While this worked for StreamElements which stopped connecting after 3 tries, Twitch chat seemed to carry on and on and on

I guess my point is make all sockets stop connecting after `maxAutomaticReconnects` ?

**Comment by MeinKraft** [comment]
ps. I love the new gui look. Took a bit of getting used to, but its very clean. Nice job

**Comment by MeinKraft** [comment]
it also seems when internet comes back on, that twitch chat never reconnects, just lots of "disconnected" notifications

**Comment by iChun** [comment]
I forgot to fix this in updates ahhhhh sorry about that!

**Comment by iChun** [comment]
Will (finally) be fixed in 1.7.0
