### ISSUE TITLE
[help] Can't find conditions/outcomes

### ISSUE THREAD

**Issue by MelanX** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#48]
![image](https://user-images.githubusercontent.com/26039509/81469756-2ad07980-91e7-11ea-8024-ec5b27268105.png)
I'm searching for conditions or outcomes. It's said that these values are documentated ingame but I can't find any.

**Comment by iChun** [comment]
Click on the + to try adding one. Also you should be using constants if you
don't know what they're for. Check out the defaults for the configs you
have set up.

**Comment by MelanX** [comment]
Okay, thank you :)
