### ISSUE TITLE
Player in Death Screen, so queue the events

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#50]
Is there a way to queue events so that when a player respawns the events happen

Ive noticed that while the player is in the death screen, things like chance cubes will appear in their hotbar, but when they respawn their hot bar is empty

Also summoning lightening fails if the player is in the death screen

these are just a couple of examples that I use in my CCI scripts

**Comment by iChun** [comment]
In 1.6.0 I've added a "health" selector for TargetCondition now, you can check that, , but to outright pause events when the player is dead, I'm afraid not. 

Most of the events are supposed to happen, some even happen when you're in the main menu, so I wasn't too keen on singling out something to checking if the player was alive or not. Hope this resolved this issue
