### ISSUE TITLE
Number Edit Text Box

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#51]
When you double click an outcome to type in a number, the gui that appears should have its textbox active, but it is not.  Also when pressing ENTER key the gui should close

This works for text entry guis but not the number ones

EG: if you create a CommandOutcome entry then double click the Command, the gui that appears already has the textbox active so you can type straight away, then pressing ENTER closes it.  This should be the same for Number guis

Thank you for the speedy update to 1.16.  Your mods are awesome !

**Comment by iChun** [comment]
Omg I finally fixed this and it was so simple 🤦‍♂️

**Comment by iChun** [comment]
Will be fixed in 1.8.0
