### ISSUE TITLE
1.16.1

### ISSUE THREAD

**Issue by WTFGaming10** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#52]
I cannot get this to work on 1.16.1.

I've done everything I can. It just will not connect to my chat or Streamlabs

**Comment by iChun** [comment]
Did you remember to put the quotes around your config values?

**Comment by WTFGaming10** [comment]
I'm using the pre-built that I found on reddit. I've put in my socket API and twitch channel name into the config. I've put quotes around it, I've done it bare, and i've also done it ["like this"] and it still isn't connecting

**Comment by iChun** [comment]
Is the console saying anything?

**Comment by WTFGaming10** [comment]
I thought there was no console on 1.16

The mod loads in game. The only option I have in game is "/cci edit" but it doesnt do anything.

Forge isnt giving me any error messages

**Comment by iChun** [comment]
The **JAVA** console.

The 1.16 version has no GUIs for the time being. If you're unfamiliar with CCI you should consider getting things working on the 1.15.2 version for now, those configs (both the toml and json files) will work on the 1.16 version.

**Comment by WTFGaming10** [comment]
I've tried that. It still doesnt work. I'm sure it's something that I'm doing wrong. I just cant figure out what.

When I load it in 1.15.2 the GUI says "no socket or chat found" but I've put my socket into the config

**Comment by iChun** [comment]
It still sounds like a config issue. Have you tried using a different text editor? I can't say for sure what's going on unless I read your logs as well.

**Comment by WTFGaming10** [comment]
I use notepad++ for editing. How do I get you the logs?

**Comment by iChun** [comment]
They're in the logs folder?

**Comment by WTFGaming10** [comment]
Initialising. Log types: cci, debug, event, socket_status, socket_event
Constants file does not exist. Creating.
No socket tokens or chat channels found. Cannot initialise.

That’s what in the log folder

Over and over and over again

**Comment by iChun** [comment]
The *other* logs folder. The Minecraft one, not the CCI one.

**Comment by WTFGaming10** [comment]
Oh ok
________________________________

**Comment by WTFGaming10** [comment]
I removed the chat lines because I don’t think they are relevant. If you actually need them, let me know and I’ll put them back in.

I really appreciate you helping. I know this is caused by my own stupidity and not the mod itself.

**Comment by iChun** [comment]
This doesn't seem to be a full log.

**Comment by iChun** [comment]
Are you sure you're editing the right config and you're saving it properly?

**Comment by WTFGaming10** [comment]
I’m plugging my token into “contentcreatorintegration.cfg” and editing the “streamlabs.json” with all of the fun things

here is the cfg file. I took out my stream key for privacy reasons

**Comment by WTFGaming10** [comment]
Also, I realized I sent you the wrong log. That was the vanilla log. Here is the log when I loaded forge and the mod and I also included the debug too in case that helps

**Comment by iChun** [comment]
What version of CCI are you using?

**Comment by WTFGaming10** [comment]
1.16.1 - 1.5.10 NOGUI
________________________________

**Comment by iChun** [comment]
Well, the config file you put here is for a very very old version of CCI for MC 1.12.2

**Comment by WTFGaming10** [comment]
Do you have a more current version?
________________________________

**Comment by WTFGaming10** [comment]
I just removed the mod and reinstalled it. I placed the mod in the folder and started the game. The only file that appeared in the config folder is “constants” – no config file populated

**Comment by iChun** [comment]
Where did you even get the version you're running right now?!

**Comment by WTFGaming10** [comment]
Curseforge?
________________________________

**Comment by iChun** [comment]
Then why do you have such an old config from an old version of CCI?

**Comment by iChun** [comment]
The way things are going right now, I'd like to suggest starting clean, or trying it on a fresh instance.

**Comment by WTFGaming10** [comment]
The first time I installed the mod, that is the config file that was created.

Where do I get the updates config?

________________________________

**Comment by iChun** [comment]
You use the updated versions. Forge no longer uses cfg files for configs
from 1.14 onwards, their config files are toml files now.

**Comment by WTFGaming10** [comment]
I tried that, and no config file generated. Only the "constants" file was created.

I'll try on 1.15 to see if I have any better luck with that.

You said 1.15 and 1.16 use the same config, right?
________________________________

**Comment by WTFGaming10** [comment]
I got it connected! That was the issue. I didn’t know I had to use the toml file. I plugged my stuff in there and it connected just fine.

Thanks so much for your help! You’re a life saver

**Comment by WTFGaming10** [comment]
Is there somewhere I can make a donation for your time?

**Comment by iChun** [comment]
Glad everything finally got sorted out. A donation isn't necessary but if you'd like you can go through the Donate link on the Curseforge page for CCI, or from the Tips link on [my Twitch](https://www.twitch.tv/ohaiichun/about). Closing this issue now since it's resolved.
