### ISSUE TITLE
KeyPressOutcome Issue

### ISSUE THREAD

**Issue by ChosenArchitect** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#55]
I am able to get the key.forward to work but when I try and use key.drop it will not hold down the drop item button that is q by default. I am using key.drop for the keyName and its pressed state is true. I know I can use the inventory outcome but I need the outcome to be client-side only. Thanks btw for adding the setting outcomes!

**Comment by iChun** [comment]
This should be fixed in 1.6.1, and I added some other ways to press keys as well. Feel free to reopen if it's not working!
