### ISSUE TITLE
[1.16.1-1.6.x] DonationAlerts wrong default JSONs.

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#56]
Hello, DonationAlerts integration works as intended and expected, but default JSON is wrong and doesn't work at all.
Let's go deeper into the problem:
Default JSON which is creating after launching the Minecraft:
```json
{
  "configs": [
    {
      "types": {}
    },
    {
      "types": {
        "donation": [
          {
            "conditions": [],
            "outcomes": [
              {
                "message": "Hey $streamer, $username just tipped amount_formatted!",
                "type": "chat"
              }
            ]
          }
        ]
      }
    }
  ],
  "init": [],
  "type": "donationalerts"
}
```
This default JSON cannot be loaded properly and CCI recogizes this as empty event and nothing happens if creating events based on this JSON.
If I take the 1.15.2 version and change a bit into like this: 
```json
{
  "configs": [
    {
      "types": {
        "donation": [
          {
            "name": "Test Event",
            "conditions": [],
            "outcomes": [
              {
                "message": "Hey $streamer, $username just tipped $amount!",
                "type": "chat"
              }
            ]
          }
        ]
      }
    }
  ],
  "init": [],
  "type": "donationalerts"
}
```
Using this JSON from 1.15.2 (with a bit of editing) - everything works perfectly, Even creating new events based on this JSON

Forge: 32.0.97
CCI: 1.16.1-1.6.0 or 1.16.1-1.6.1
Solution for this issue: change broken JSON to normal one.
(Also it is hard to create more than 19 events (on Full HD monitor) on the CCI GUI,  I'll create another issue about this a bit later)

**Comment by iChun** [comment]
Fixed on my end. Sorry about this, remnants from copying the Streamlabs config, heh. Will be fixed in 1.7.0
