### ISSUE TITLE
[Question] 1.15.2

### ISSUE THREAD

**Issue by avidgamer5918** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#57]
Hello, I was wondering If It Is still possible to do rewards triggered by twitch channel points redemptions? If so how does one go about setting it up? I tried doing it the way it was done in 1.12 but I can not get it to work.
Thank you and have a good day
-AvidGamer

**Comment by iChun** [comment]
It should still be possible, yes. Twitch chat hasn't changed anything as
far as I know. You just have to keep a look out for the channel reward id.

**Comment by avidgamer5918** [comment]
I tried to set it up so that if a person redeem a reward called creeper ssss it would play the creeper primed sound. I tried with both a variable check and a message check. I used custom-reward-id as the variable name and then used the reward id # as the variable result. I am not sure what I am setting up wrong but i can not get it to work. 
Thank you 
-AvidGamer

**Comment by Qeelin** [comment]
First you create a new channel point custom reward that people can purchase. You will need to make sure and turn on the switch to require viewer to enter text. After that, you need to redeem it once with your game open. Then open up the latest CCI log and look at the last entry. You will see custom-reward-id listed there. Copy that ID number. Create a new event in CCI in the text area. You will create a variable condition with the variable ID as "custom-reward-id" and put that crazy long ID you copied earlier in the ID area. Then the event will trigger when someone buys it.

**Comment by iChun** [comment]
Yep, what Qeelin said. Thanks Qeelin!

**Comment by avidgamer5918** [comment]
Okay I will try that. Thank you

**Comment by avidgamer5918** [comment]
I must be doing something wrong I still can't get it to work

**Comment by sublimiter** [comment]
Did you create a new event in the "message" type in the Chat section of CCI? If it's either in the Streamlabs section or not in the specific "message" event type in the Chat section, it will not work.

**Comment by avidgamer5918** [comment]
That worked. Thank you
