### ISSUE TITLE
1.16.2 / Forge 33.0.20 Loading error

### ISSUE THREAD

**Issue by StyLexR6** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#58]
The mod pulls up a toast error on 1.16.2, which crashes the game during launch.

[crash-2020-08-27_15.12.56-client.txt](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/files/5136892/crash-2020-08-27_15.12.56-client.txt)

**Comment by iChun** [comment]
This has been fixed for 1.16.3+. Sorry!
