### ISSUE TITLE
Unable to insert variables into Arithmetic Conditions

### ISSUE THREAD

**Issue by ChachavaMC** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#6]
This may be user error on my part but I've tried every way I could think to get this working with no luck. I've been trying to take a number from a chat message, perform some basic arithmetic on the number, and use the output as a variable elsewhere. I've checked the $message variable using an isNumber condition to make sure it's a number, then used an arithmetic condition to (as an example) add 50 to the number and stored it in the variable "testVar". I've then output testVar in chat and regardless of the input (provided it was a number that was entered) It always returns 50.0. I've tried all variable names both with and without preceding $'s and I'm still not getting the expected results. 

Hopefully this made sense, and apologies if this is an error on my part, but I've been tearing my hair out trying to figure this out.

**Comment by iChun** [comment]
Letting me see the JSON file would help to make sure everything is done
properly if you're okay with sharing that. Maybe even just the condition
itself.

I'm not sure but I also think there is a small bug with the condition that
I was planning on fixing for the next update.

**Comment by ChachavaMC** [comment]
It won't let me upload a JSON file directly apparently so hopefully a pastebin will be OK. Still testing out possibilities at the moment so not much to see, it's the 'numberTest' event that's causing the problems.

https://pastebin.com/Pp9Zv9QF

also, I should note that the arithmetic condition works fine when numbers are entered directly, it only has issues when they're entered as variables. Hope this helps.

**Comment by iChun** [comment]
If I remember correctly, you don't need to put the "$" in, so just
"message" is fine, but there is an issue with the condition reading a
number that is a in a string, and that was what I needed to fix for the
next update. That might be why it isn't working.

I'd say if it still doesn't work with removing the $, wait for the next
update and give it a shot?

**Comment by ChachavaMC** [comment]
I'm getting the same outcome without the $, next update it is then :) Thank you for the swift reply and also for the work put into the mod.

**Comment by iChun** [comment]
Hopefully fixed. Slated for v1.0.1
