### ISSUE TITLE
Health and Armour Variables please

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#60]
Could we please have some variables that read the player's Total Number of Hearts and Total Armour Values?

This would allow us to spawn harder mobs depending on the players number of hearts and armour level, because some mods add extra hearts the player can become too over powered for the mobs. I would like to try and balance this

Thank You

**Comment by iChun** [comment]
You previously could get health from TargetCondition. I'll add armor to it as well. Will be available in 1.7.0
