### ISSUE TITLE
.toml error

### ISSUE THREAD

**Issue by zetisky** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#63]
When I start the mod for the first time, instead of the .cfg file that appears on tutorials there is a .toml one, when by its default, minecraft runs fine, but when I put my Socket API or my twitch user name in the .toml file when I run minecraft it automatically crashes

**Comment by iChun** [comment]
Minecraft Forge updated their config files to use the toml format instead of the cfg format. Your fields/strings etc will require quotes around them now.

In cfg you could just put a name like:
`zetisky`

Now in toml you have to add quotes:
`"zetisky"`
