### ISSUE TITLE
1.16.5 Notification Spam

### ISSUE THREAD

**Issue by SlenderGuardian** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#65]
Hi, I'm new to CCI and was wondering what it is I am doing wrong. I just installed the mod to my Minecraft which is 1.16.5 and when I do a test for any notification, it gets spammed. Any idea on what is causing this?

![Help2](https://user-images.githubusercontent.com/82261689/114264521-47010b80-99a0-11eb-919c-8e15ecbd219a.png)

![Help](https://user-images.githubusercontent.com/82261689/114264479-0e613200-99a0-11eb-889c-152f63888107.png)

**Comment by iChun** [comment]
Stream Elements? They send 5 slightly different test events. In a real
world scenario it only pops up once I think. You'll have to try and figure
out the events and their types. Dumping events and reading the log should
help.

**Comment by SlenderGuardian** [comment]
This is the log from the config folder. I'm still new so I don't know where to find the Dumping events.

https://github.com/SlenderGuardian/Log/issues/1#issue-855025594

**Comment by iChun** [comment]
I had a look at your log, it was as I said, Stream Elements test event spits out 5 times, slightly different each time. The type is "follow" for all 5, but the "listener" is different every time.

It's not really easy to help you out here, this issue tracker is more meant for crashes with the mod or unexpected behaviour. If you have a discord account could you kindly join my discord server here: https://discord.gg/2uNeQ4j3Rn

We have a channel dedicated to helping people with CCI config issues, so a bunch of other people might be able to assist as well.
