### ISSUE TITLE
Sky Bees Modpack GUI crash on launch

### ISSUE THREAD

**Issue by MFWalter** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#66]
I do not know if it is the CCI mod or the Modpack, but when I add CCI to the Sky Bees modpack I get a crash during the loading.
https://www.curseforge.com/minecraft/modpacks/sky-bees

[crash-2021-04-23_21.39.17-client.txt](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/files/6369724/crash-2021-04-23_21.39.17-client.txt)
[crash-2021-04-23_21.40.49-client.txt](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/files/6369725/crash-2021-04-23_21.40.49-client.txt)
[crash-2021-04-23_21.42.13-client.txt](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/files/6369726/crash-2021-04-23_21.42.13-client.txt)
[crash-2021-04-23_21.45.07-client.txt](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/files/6369727/crash-2021-04-23_21.45.07-client.txt)
[crash-2021-04-23_21.49.42-client.txt](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/files/6369728/crash-2021-04-23_21.49.42-client.txt)
[crash-2021-04-23_22.00.52-client.txt](https://github.com/iChun/ContentCreatorIntegration-IssuesAndDocumentation/files/6369729/crash-2021-04-23_22.00.52-client.txt)

**Comment by MeinKraft** [comment]
you've made a mistake in your config file. You have to be careful of stray charactors, or missing charactors like " or { } or commas

`Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid value: MFWalter`

**Comment by MFWalter** [comment]
WOW! Thanks MeinKraft. I read the file multiple times and failed at that. I just completely misunderstood the instructions. It says 
#REMEMBER to add quotes around your token.
in the instructions, but then the variable{?} is called twitchChats now {something}Token so it simply didn't occur to me that I needed quotes despite spending multiple hours attempting to find and fix the issue.
