### ISSUE TITLE
Mouse Handler Event Crash

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#67]
Forge: 36.1.16
CCI: 1.16.5-1.7.1
MC: 1.16.5

When I go to add an event outcome I frequently get "mouseReleased event handler" crash. Happened 3 times in a row.  Seems to be the screen where you choose the type of outcome, the "Add Outcome" list screen

Crashlog: https://pastebin.com/JeixmK8r

**Comment by iChun** [comment]
Can you attach your json files? I can't seem to reproduce this on my end.

**Comment by MeinKraft** [comment]
https://pastebin.com/heSAasue  this is the "chat" section.  I copied the text from an outcome ready to paste into a new CommandOutcome in the "!back" event and boom, crash

**Comment by MeinKraft** [comment]
and typically I cant get cci to crash now,  but it has happened a couple of times

**Comment by iChun** [comment]
If you happen to have a clip/video of this happening, I'd like to see it too. I'll try and see where in the code is crashing but it might be tough to fix without being able to repro

**Comment by MeinKraft** [comment]
I was trying to video it, lol and now it wont happen.  But i'll do my damndest to video it as proof im not going mad

**Comment by iChun** [comment]
Should be fixed in 1.8.0

**Comment by MeinKraft** [comment]
oh nice.  I tried several times for the crash to happen again but it wouldnt.  Did it 3 times in a row then worked perfectly fine.
