### ISSUE TITLE
[Feature Request] Check Curios for an item

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#68]
Would it be possible to add a CuriosConditionalOutcome?  So if the streamer is wearing a poison antidote charm in a Curio slot, for example, I give streamer hunger instead of poison

or if they are not wearing a poison antidote charm I poison them ?

the condition would check Curios for a specific item such as "bountifulbaubles:bezoar"

maybe even a CurioDropOutcome?

Like the InventoryOutcome but for Curios and Baubles

**Comment by iChun** [comment]
I'll have to look into how they do their inventories

**Comment by iChun** [comment]
Have you seen how they do their commands? https://github.com/TheIllusiveC4/Curios/wiki/Commands

It's doesn't really fit your description but I was wondering how much you could do through those. Don't think I can get CCI to support their inventory without directly adding a dependency for that mod

**Comment by MeinKraft** [comment]
I think the lock/unlock command would be useful. I'll have to do some testing.  I was thinking more of a specific item being locked/dropped, but locking a slot, such as charm slot, might still achieve the same effect...
