### ISSUE TITLE
Confused with Connections

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#69]
Forge 36.1.2
CCI: 1.16.5-1.7.2

Im a little confused with the "connections" button in cci

If you disconnect (for whatever reason) the sockets, for me twitch chat and streamelements, there is no way to reconnect them because they get removed from the list. This means a minecraft restart

For the same reason if the sockets disconnect themselves, ie loss of internet connection or twitch/streamelements being weird you need to restart minecraft. the socket shows as errored but the reconnect button does not reconnect the sockets. Simply says failed to reconnect and removes the socket from the list.

Im guessing "connections" is supposed to allow us to reconnect manually?  The auto reconnect attempts usually say "disableing reconnects" long before my internet connection comes back to life

**Comment by iChun** [comment]
You have to force reconnect all as a workaround.

**Comment by MeinKraft** [comment]
sorry, but how do i do this?

**Comment by iChun** [comment]
Shift click reconnect
