### ISSUE TITLE
floor, ceil, round arithmetic conditions not working

### ISSUE THREAD

**Issue by ChachavaMC** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#7]
This again may be user error but I can't find a way to make them work. The functions will generally only need a single value given to them, but the arithmetic condition will only be accepted with 2 values entered. I've tried leaving a null in the 2nd value field, this leaves the condition highlighted in red and it gets removed when you save and close the config. I've tried adding a 0 in to the 2nd value field (https://pastebin.com/19E46z99) this gives a result of 0 in the toast. And I've tried adding in the same number in both value fields (https://pastebin.com/NsSLnkGq), which also gives a 0 in the toast. 

Is there something I'm missing with this?

**Comment by iChun** [comment]
I just looked at the code again. Yeah whoops that's not gonna work. I'll
fix for the next update.

**Comment by iChun** [comment]
Making a note to do min max functions as well.

**Comment by iChun** [comment]
Fixed for 1.0.2.
