### ISSUE TITLE
Streamelements "emulate" follow and displayName bug

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#70]
Forge: 36.1.2
CCI: 1.16.5-1.7.2

So using the "Emulate" button from the Streamelements website ive noticed the 'follow' does not trigger. It shows up in the event viewer but does not trigger my cci rewards, which is a message on screen and a firework. Through Twitch this works fine

Also

When using the emulate for subs, cheers etc, the $displayName variable is empty. The $name variable is not. When used through Twitch the $displayName variable is filled and $name is empty, reverse of the emulate

This of course caused me to change my scripts from $displayName to $name which worked for the emulate, but Twitch was of course wrong, all the mobs spawned as "$name", so I had to change back to "$displayName"

Could you maybe simplify this and have both StreamElements and StreamLabs use $name ?  I dont use $user for displaying the twitch vewers name because I prefer the formatted look, so my name would be "CrimsonFluff" not "crimsonfluff"

**Comment by MeinKraft** [comment]
it seems the cci-type-event for streamelements emulate is 'follower' but through Twitch its 'follow'

**Comment by iChun** [comment]
StreamElement test events do not always match their real world events, I've noticed. I've set the default generated files to the right types as far as I'm aware. You're best to work off actual events as they come through, the raw data will be in the log file and you can dump the variables whilst it's still cached through the Event Viewer.

If they do mismatch, please let me know and attach logs/dump.json.

Consider checking out the VariableInsertionCondition and Constants if you'd like to try and have multiple types that do the same thing.

**Comment by MeinKraft** [comment]
Im using the VariableInsert and Constants so my events are compatible between StreamLabs and StreamElements as I make scripts for a couple of streamers

It was just frustrating at first when twitch, streamlabs and streamelements use different variables...  but im working with it

thanks

**Comment by iChun** [comment]
If you thought that was frustrating, how do you think I felt having to code and test it all? :)

**Comment by MeinKraft** [comment]
Holding a medical degree and being able to code a mod that I suspect is knee deep in recursion, to give us a vast array of options, is a testament to how clever you are.

I can only say Thank You for the hours of Minecraft torture you have allowed me to dump on my fellow Twitch streamers!  

Thank You

**Comment by iChun** [comment]
You're welcome :)

**Comment by MeinKraft** [comment]
you should be asleep - I caught the end of your stream, 10hours + !!
