### ISSUE TITLE
Trouble updating in server environment 

### ISSUE THREAD

**Issue by CKY-** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#71]
Minecraft version: 1.16.5
Forge version:  36.1.9

Problem: When  updating from  CCI version ContentCreatorIntegration-1.16.5-1.7.1.jar to ContentCreatorIntegration-1.16.5-1.7.2.jar 
on a server  the server errors out, here are the logs. 

Please advise.. How to rectify this error 
crash log: https://gist.github.com/CKY-/b93dc80ed2ec12680c0f58e87dd656e8

Debug log; part 1 : https://gist.github.com/CKY-/c2d34aea1f80d575632e1bd7b2fb8871

part 2 : https://gist.github.com/CKY-/20dabc323578313ca4419f63d9ccee6b

Thank you

**Comment by iChun** [comment]
That's.... An odd crash... I'm sure you've tried redownloading from
Curseforge. You could try a clean server to see if that fixes things too,
but if that doesn't, you can use 1.7.1 on the server and use 1.7.2 on the
client perfectly fine.

Just be mindful that keeping 1.7.1 on the server will make InventoryOutcome
use the behaviour on that version and StringContains and StringCompareTo
conditions to not work. Everything else should work fine.

**Comment by iChun** [comment]
I can see why it's crashing. Will be fixed in 1.8.0
