### ISSUE TITLE
Splashscreen and unreadable toasts

### ISSUE THREAD

**Issue by MeinKraft** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#72]
Forge 36.1.17
CCI: 1.16.5-1.7.2/1.8.0

Hi,  In your Fabric version you moved your INIT to after the splash screen loads. Could you do the same for forge and hopefully stop the toasts looking the way they do in the picture

thanks

Pic: https://imgur.com/a/pZ4lTzb

**Comment by iChun** [comment]
I'm not gonna fix that. I'm using the mods loaded event in forge to push
the toasts. I had go jump through hoops to find a reliable way to post the
toasts in Fabric because they were launching too early and ended up
erroring out so I ended up creating my own hook.

**Comment by iChun** [comment]
I'm normally would like to prioritise getting the sockets connected as
early as possible considering how long packs can take to load over a minor
rendering issue like the toasts that go away once Minecraft loads fully, in
case you're wondering. The mods loaded event is the last one-time event
that triggers up to the loading of the main menu, so I'm using that.

**Comment by MeinKraft** [comment]
fair enough.  I thought it might be a quick fix

**Comment by iChun** [comment]
If it was I wouldn't have waited till the fabric port to fix it :p
