### ISSUE TITLE
[Feature Request] Render Ores as Stone

### ISSUE THREAD

**Issue by SoniEx2** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#75]
For Reasons, the ability to have a channel points reward that makes ores render as stone sounds "Exciting!"

**Comment by iChun** [comment]
No. CCI does a lot of things but this is outside the scope that I would like CCI to do.

One other alternative would be to make a third party mod that changes the world renderer to do what you want, and also takes a command to toggle the feature.
