### ISSUE TITLE
[edge case Request] Escaping $message quotes 

### ISSUE THREAD

**Issue by CKY-** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#77]
if the user types the message escaped it works "\my message \" vs "my message"  but I don't see a way to send $message escaped for use in tell raw. Would also be cool if $color could be extended to name  for use in tell raw. Color being hex and minecraft wanting a name.. 

![reply](https://cdn.discordapp.com/attachments/729544171509252158/881615904302047322/unknown.png)

![chat](https://cdn.discordapp.com/attachments/729544171509252158/881615799230541954/unknown.png)

**Comment by iChun** [comment]
Use the JsonSafeCondition to convert the entire variable's string for use in the tell raw command.
