### ISSUE TITLE
1.12.2 Wizard is not popping up

### ISSUE THREAD

**Issue by YoYoawe** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#80]
when I launch CCI in 1.12.2 the wizard wont pop up same as in 1.18 I have tried everything from starting a clean boot of minecraft to booting it from Curseforge if anyone has a fix to this please let me know

**Comment by iChun** [comment]
The Wizard doesn't exist in 1.12.2's version of CCI.

In 1.18 if you missed the first run setup prompt then you may access it by going to CCI's configs (either using the /cci command ingame or editing CCI's mod configs from the mod screen), opening the help window and then clicking on the setup wizard button.

**Comment by iChun** [comment]
Optionally you can also change the first run config in the config file, which is what CCI uses to remember if you're been shown the prompt before or not.
