### ISSUE TITLE
YouTube chat connected but no chat tab

### ISSUE THREAD

**Issue by ghost** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#81]
MC - 1.18.2
Forge - 40.0.36
CCI - 1.9.3

so when you connect to StreamElements you get a default list of events created as seen in the pic, in a "StreamElements" tab

when you connect to YouTube chat, there is nothing.
I went through the google thing of getting an API key, and I also enabled YouTube Data API v3 in case that was needed
I had a live stream running, ran Minecraft, CCI said YouTube chat was connected
In the log it says "Missing event configuration: chat".

I'm sure I've missed something...

pictures - https://imgur.com/a/6AdnTKM
log from cci folder  - https://pastebin.com/g9vUPPnB

**Comment by iChun** [comment]
Okay I had a look at the code and oddly enough, I never load up the configuration file when connecting to YouTube Chat. 

You can work around this for the time being by passing a Twitch channel to connect via chat, maybe a quiet/dead chat so you don't randomly get events from there. You should be able to see YouTube chat events after that.

**Comment by CrimsonFluff** [comment]
ok Thanks

**Comment by iChun** [comment]
Fixed in 1.10
