### ISSUE TITLE
Motion Outcome ignores relative attribute

### ISSUE THREAD

**Issue by RikuNGNL** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#83]
If you try to add motion to the player in the direction they are facing, it doesn't work. 
Only the fixed world coordinates work. Tested on players and entities in single player. 

Version: 1.10.2

**Comment by iChun** [comment]
Relative is relative to the entity's current motion, not the direction they
are facing.

If you want it to be relative to the direction they're facing then you'll
have to get the look vector using the Target Condition first and use those
values
