### ISSUE TITLE
Follower event not working StreamElements overlay test

### ISSUE THREAD

**Issue by xerminator** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#87]
Steps to reproduce:
- install the mod and do fresh setup with streamelements
- Make a overlay on streamelements
- Emulate a follower event
- No message being sent to minecraft
Expected Result
A message being sent to Minecraft with the values you have set in CCI config

The subs/raid/host/tip etc.. all work, only the follower does not afaik.

If you look in the events tab it does show up there but the event for follower still won't fire.

Minecraft version: 1.19.2
Version: 1.11.0

**Comment by iChun** [comment]
Intentional. As per the docs: 
![image](https://user-images.githubusercontent.com/2298444/227755869-4fd7afef-2bc1-4de5-b799-d361db9210cc.png)

Live follow events use a different event type key than the test events.
