### ISSUE TITLE
RandomNumberCondition requres value2 to be 1+ value 1

### ISSUE THREAD

**Issue by darkphan** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#90]
Version: ContentCreatorIntegration-1.18.2-Forge-1.11.0

RandomNumberCondition seems to require value1 and value2 to be at least 1 apart. So for example if value1 is 0.5 then value2 needs to be atleast 1.5 or greater, if you use 1.0 for example it will always return value1, 0.5 in this case.

**Comment by iChun** [comment]
Fixed for v1.11.1 which will be available on MC 1.19.2 onwards. For older versions continue to use differences >=1 then divide the value in another condition. Thanks!
