### ISSUE TITLE
ContentCreatorIntegration-1.20.1-Forge-1.11.1.jar not connecting to Twtich Chat

### ISSUE THREAD

**Issue by ElderBarrySirUp** [iChun/ContentCreatorIntegration-IssuesAndDocumentation#92]
After several attempts, reinstalls and config deletions, I am not able to connect to Twitch Chat. I also tested it on ContentCreatorIntegration-1.19.2-Forge-1.11.1 and it worked just fine.

**Comment by iChun** [comment]
Is this issue still present? None of my other usual regular users seem to have any issues

**Comment by ElderBarrySirUp** [comment]
No. Sorry. Forgot to reply back. I had to just redo all my configs. For some reason it would not accept a copy paste of all my commands.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
